language: ruby
rvm:
  - 2.4
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _site
  repo: molonc/molonc.github.io
  target_branch: master
